/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110925-g45fa85a777-20230529"
#endif /* AVUTIL_FFVERSION_H */
